// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentIMS.Data;

#nullable disable

namespace StudentIMS.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20230609134349_some_students_addes")]
    partial class some_students_addes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentIMS.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "John",
                            StudentNumber = 123456,
                            Surname = "Dae"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Sam",
                            StudentNumber = 258369,
                            Surname = "Dalton"
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Name = "Paul",
                            StudentNumber = 259354,
                            Surname = "Wise"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Name = "Stacy",
                            StudentNumber = 685478,
                            Surname = "Willer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
